api/cart/urls.py
from django.urls import path

from api.cart.views import RmoveItemFromCartView, DetailCartItemView, ListCartItemsView

urlpatterns = [
    path('remove/<int:pk>/', RmoveItemFromCartView.as_view()),
    path('<int:pk>/', DetailCartItemView.as_view()),
    path('', ListCartItemsView.as_view()),
]

core/urls.py
from django.urls import path

from core.views import item_list, item_detail, add_to_cart, cart_list, cart_delete_item, \
    cart_delete_single_item, wish_list, add_to_wish_list, remove_from_wish_list, remove_from_wish_list_in_list

urlpatterns = [
    path('', item_list, name='home-page'),
    path('order_by/<str:ordering_obj>', item_list, name='order-by'),
    path('cart/', cart_list, name='cart-page'),
    path('wish_list/', wish_list, name='wish-list'),
    path('delete_from_cart/<slug>/', cart_delete_item, name='delete-from-cart'),
    path('delete_from_cart_single_item/<slug>/', cart_delete_single_item, name='delete-from-cart-single-item'),
    path('add_to_cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_to_cart/<slug>/<str:cart>/', add_to_cart, name='add-to-cart-from-cart'),
    path('category/<str:category_slug>/', item_list, name='home-page-category'),
    path('add_to_wish_list/<str:item_slug>/', add_to_wish_list, name='add-to-wish-list'),
    path('remove_from_wish_list/<str:item_slug>/', remove_from_wish_list, name='remove-from-wish-list'),
    path('remove_from_wish_list_in_list/<str:item_slug>/', remove_from_wish_list_in_list,
         name='remove-from-wish-list-in-list'),
    path('<str:category_slug>/<str:item_slug>/', item_detail, name='item-detail'),

]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('core.urls')),
    # path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    # path('auth/', include('djoser.urls.jwt')),
    path('api/v1/', include('api.routers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/cart/models.py
from django.db import models

# Create your models here.

core/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Item(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField()
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_items')
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='items/', default='default.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('item-detail', kwargs={'category_slug': self.category.slug, 'item_slug': self.slug})

    def get_discount_percent(self):
        return round(100 - (self.discount_price / self.price) * 100)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-created']


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='item_images')
    image = models.ImageField(upload_to='items/', blank=True)

    class Meta:
        verbose_name = "Фото товара"
        verbose_name_plural = "Фото товаров"

    def __str__(self):
        return '{} # {}'.format(self.item.title, self.id)


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.item.title} - {self.quantity}'

    def total_amount(self):
        return self.quantity * self.item.discount_price if self.item.discount_price else self.quantity * self.item.price


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def total_order_amount(self):
        result = 0
        for item in self.items.all():
            result += item.total_amount()
        return result


class WishItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True, null=True)
    adding_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.item.title}'

    class Meta:
        verbose_name = "Избранный товар"
        verbose_name_plural = "Избранные товары"

api/cart/views.py
from rest_framework import generics, permissions, views, response
from django.utils import timezone

from api.cart.serializers import CartSerializser
from api.items.serializers import ItemDetailSerializer
from core.models import Item, Order, OrderItem


class ListCartItemsView(generics.ListAPIView):
    """ List items in cart
    """
    serializer_class = CartSerializser
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, ordered=False)


class DetailCartItemView(views.APIView):
    """ Detail cart item, add item to cart and delete single item from cart
    """
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, pk):
        try:
            instance = OrderItem.objects.get(item_id=pk, user=request.user, ordered=False).item
        except OrderItem.DoesNotExist:
            return response.Response(status=404)
        serializer = ItemDetailSerializer(instance)
        return response.Response(serializer.data)

    def post(self, request, pk):
        try:
            item = Item.objects.get(id=pk)
        except Item.DoesNotExist:
            return response.Response(status=404)
        order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item.quantity += 1
                order_item.save()
                return response.Response(status=201)
            else:
                order.items.add(order_item)
                return response.Response(status=201)
        else:
            ordered_date = timezone.now()
            order = Order.objects.create(user=request.user, ordered_date=ordered_date)
            order.items.add(order_item)
            return response.Response(status=201)

    def delete(self, request, pk):
        try:
            item = Item.objects.get(id=pk)
        except Item.DoesNotExist:
            return response.Response(status=404)
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
                if order_item.quantity == 1:
                    order.items.remove(order_item)
                    order_item.delete()
                    return response.Response(204)
                else:
                    order_item.quantity -= 1
                    order_item.save()
                return response.Response(204)
            else:
                response.Response(400)
        else:
            response.Response(400)


class RmoveItemFromCartView(views.APIView):
    """ Remove item from cart
    """
    permission_classes = [permissions.IsAuthenticated]

    def delete(self, request, pk):
        try:
            item = Item.objects.get(id=pk)
        except Item.DoesNotExist:
            return response.Response(status=404)
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.items.filter(item__slug=item.slug).exists():
                order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
                order.items.remove(order_item)
                order_item.delete()
                return response.Response(status=204)
            else:
                return response.Response(status=400)
        else:
            return response.Response(status=400)

core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from core.models import Item, Category, OrderItem, Order, WishItem

current_path = ''


def item_list(request, category_slug=None, ordering_obj=None):
    categories = Category.objects.all()
    wish_items = []
    if request.user.is_authenticated:
        wish_items = [item.item for item in WishItem.objects.filter(user=request.user)]

    if category_slug:
        category = Category.objects.get(slug=category_slug)
        items = Item.objects.filter(category=category)
    else:
        if ordering_obj:
            if ordering_obj == 'sale':
                items = [item for item in Item.objects.all() if item.discount_price]
            else:
                items = Item.objects.all().order_by(ordering_obj)
        else:
            items = Item.objects.all().order_by('category')
        category = None

    if request.GET:
        if request.GET.get('sale'):
            items = items.filter(discount_price__isnull=False).order_by('-price')

    search_query = request.GET.get('search', '')
    if search_query:
        items = Item.objects.filter(title__icontains=search_query)

    context = {
        'items': items,
        'categories': categories,
        'wish_items': wish_items,
        'category': category
    }
    global current_path
    current_path = request.path
    return render(request, 'core/home.html', context)


def item_detail(request, item_slug, category_slug):
    item = Item.objects.get(slug=item_slug)
    category = Category.objects.get(slug=category_slug)
    wish_items = []
    if request.user.is_authenticated:
        wish_items = [item.item for item in WishItem.objects.filter(user=request.user)]
    context = {
        'item': item,
        'category': category,
        'wish_items': wish_items,
    }
    global current_path
    current_path = request.path
    return render(request, 'core/item_detail.html', context)


def cart_add_redirect(request, item):
    messages.success(request, f'Product has been added to cart')
    if current_path == '/':
        return redirect('home-page')
    else:
        return redirect(item.get_absolute_url())


@login_required
def add_to_cart(request, slug, cart=None):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            if cart:
                return redirect('cart-page')
            else:
                return cart_add_redirect(request, item)
        else:
            order.items.add(order_item)
            if cart:
                return redirect('cart-page')
            else:
                return cart_add_redirect(request, item)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        if cart:
            return redirect('cart-page')
        else:
            return cart_add_redirect(request, item)


@login_required
def cart_delete_item(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, 'Product has been deleted from order')
            return redirect('cart-page')
        else:
            messages.info(request, 'This product is not in your cart')
            return redirect('cart-page')
    else:
        messages.info(request, 'You haven\'t got active order')
        return redirect('cart-page')


@login_required
def cart_delete_single_item(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            if order_item.quantity == 1:
                order.items.remove(order_item)
                order_item.delete()
                messages.info(request, 'This item has been remove from your cart')
            else:
                order_item.quantity -= 1
                order_item.save()
            return redirect('cart-page')
        else:
            messages.info(request, 'This product is not in your cart')
            return redirect('cart-page')
    else:
        messages.info(request, 'You haven\'t got active order')
        return redirect('cart-page')


@login_required
def cart_list(request):
    order = Order.objects.filter(user=request.user, ordered=False)
    items = order[0].items.all().order_by('item__title')
    context = {
        'items': items,
        'order': order[0]
    }
    return render(request, 'core/cart.html', context)


@login_required
def wish_list(request):
    wish_items = WishItem.objects.filter(user=request.user).order_by('-adding_date')
    context = {
        'wish_items': wish_items,
    }
    return render(request, 'core/wish_list.html', context)


@login_required
def add_to_wish_list(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    WishItem.objects.create(user=request.user, item=item)
    messages.info(request, 'Item was added to your Favorites')
    return redirect('home-page')


@login_required
def remove_from_wish_list(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    wish_item = WishItem.objects.get(user=request.user, item=item)
    wish_item.delete()
    messages.warning(request, 'Item was removed form your Favorites')
    return redirect('home-page')


@login_required
def remove_from_wish_list_in_list(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    wish_item = WishItem.objects.get(user=request.user, item=item)
    wish_item.delete()
    messages.warning(request, 'Item was removed form your Favorites')
    return redirect('wish-list')

templates/core/cart.html
{% extends 'base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h3>Some navigationbar</h3>
		</div>
	<div class="col-md-9">
		<div class="container my-1 py-3 z-depth-1 rounded">

		  <!--Section: Content-->
		  <section class="dark-grey-text">

		    <!-- Shopping Cart table -->
		    <div class="table-responsive">

		      <table class="table product-table mb-0">

		        <!-- Table head -->
		        <thead class="navbar-dark orange lighten-2">
		          <tr>
		            <th></th>
		            <th class="font-weight-bold">
		              <strong>Product</strong>
		            </th>
		            <th class="font-weight-bold">
		              <strong>Sale</strong>
		            </th>
		            <th></th>
		            <th class="font-weight-bold">
		              <strong>Price</strong>
		            </th>
		            <th class="font-weight-bold">
		              <strong>Count</strong>
		            </th>
		            <th class="font-weight-bold">
		              <strong>Sum</strong>
		            </th>
		            <th></th>
		          </tr>
		        </thead>
		        <!-- /.Table head -->

		        <!-- Table body -->
		        <tbody>

		          <!-- First row -->
		          {% for item in items %}
		          <tr>
		            <th scope="row">
		              <img src="{{ item.item.image.url }}" alt="" class="img-fluid z-depth-0 img-thumbnail" style="max-width: 70% !important; " alt="thumbnail">
		            </th>
		            <td>
		              <h5 class="mt-3">
		                <strong>{{ item.item.title|truncatechars:20 }}</strong>
		              </h5>
		              <p class="text-muted">{{ item.item.category }}</p>
		            </td>

		            {% if item.item.discount_price %}
		            	<td><span class="red-text">sale:</span> {{ item.item.get_discount_percent }}%</td>
		            {% else %}
		            	<td><span class="red-text">sale:</span> 0%</td>
		            {% endif %}	

		            <td></td>
		            {% if item.item.discount_price %}
		            	<td>${{ item.item.discount_price }}</td>
		            {% else %}
		            	<td>${{ item.item.price }}</td>
		            {% endif %}


		            <td  align="center">
						<div class="mb-2"><a href="{% url 'add-to-cart-from-cart' item.item.slug 'cart' %}" class="btn btn-outline-amber btn-sm"><i class="fas fa-angle-up"></i></a></div>
						<div class="mb-1">{{ item.quantity }}</div>
						<div><a href="{% url 'delete-from-cart-single-item' item.item.slug %}" class="btn btn-outline-amber btn-sm"><i class="fas fa-angle-down"></i></a></div>
		            </td>
		            <td class="font-weight-bold">
		              <strong>${{ item.total_amount }}</strong>
		            </td>
		            <td>
						<a href="{% url 'delete-from-cart' item.item.slug %}" class="red-text btn-sm"><i class="fas fa-trash mr-2" aria-hidden="true"></i></a>
		            </td>
		          </tr>
		          {% endfor %}
		          <!-- /.First row -->

		          <!-- Fourth row -->
		          <tr>
		            <td colspan="3"></td>
		            <td>
					{% if order %}
		              <h4 class="mt-2">
		                <strong>Total</strong>
		              </h4>
		            </td>
		            <td class="text-right">
		            	<h4 class="mt-2">
		            		<strong>{{ order.total_order_amount }}$</strong>
		            	</h4>
		            </td>

		            <td colspan="3" class="text-right">
		            	<button class="btn btn-outline-warning waves-effect btn-md ml-0">
							<a href="#" class="amber-text"> Complete order<i class="fas fa-angle-right right"></i></a>
						</button>
		            </td>
		            {% else %}
		            	<h4>There are not items in your cart </h4>
					{% endif %}
		          </tr>
		          <!-- Fourth row -->

		        </tbody>
		        <!-- /.Table body -->

		      </table>

		    </div>
		    <!-- /.Shopping Cart table -->

		  </section>
		  <!--Section: Content-->

		</div>
	</div>
	</div>
</div>
{% endblock content %}

templates/core/item_detail.html
{% extends 'base.html' %}

{% block title %}{{ item.title }} - {{ item.category }}{% endblock %}

{% block content %}
<div class="container my-5 py-5 z-depth-1">

  <!--Section: Content-->
  <section class="text-center">

    <!-- Section heading -->
    <h3 class="display-4 category-title-detail"> Category: {{ item.category.title }} </h3>
    <hr class="mb-5 orange lighten-1" style="width: 83%">
    <div class="row">

      <div class="col-lg-6">

        <!--Carousel Wrapper-->
        <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">

          <!--Slides-->
          <div class="carousel-inner text-center text-md-left" role="listbox">
            <div class="carousel-item active">
              <img src="{{ item.image.url }}"
                alt="First slide" class="img-fluid">
            </div>
            {% for image in item.itemimage_set.all %}
            <div class="carousel-item">
              <img src="{{ image.image.url }}"
                alt="Second slide" class="img-fluid">
            </div>
            {% endfor %}
          </div>
          <!--/.Slides-->

          <!--Thumbnails-->
          <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
          <!--/.Thumbnails-->

        </div>
        <!--/.Carousel Wrapper-->

        <div class="row mt-4">
          <div class="col-md-12">

            <div class="row">
              <a href="{{ item.image.url }}" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4 mb-2">
                  <img src="{{ item.image.url }}" class="img-fluid rounded">
              </a>
              {% for image in item.itemimage_set.all %}
              <a href="{{ image.image.url }}" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4 mb-2">
                  <img src="{{ image.image.url }}" class="img-fluid rounded">
              </a>
              {% endfor %}
            </div>

          </div>
        </div>

      </div>

      <div class="col-lg-5 text-center text-md-left">

        <h2 class="h2-responsive text-center text-md-left product-name font-weight-bold dark-grey-text mb-1 ml-xl-0 ml-4">
          <strong>{{ item.title }}</strong>
        </h2>
        <span class="badge badge-pill badge-warning product mb-4 ml-xl-0 ml-4 mr-1">{{ item.category.title }}</span>
        {% if item.discount_price %}
			   <span class="badge badge-pill badge-danger my-3 mr-2">Sale</span>
		    {% endif %}	

        {% if item.discount_price %}
        <h3 class="h3-responsive text-center text-md-left mb-5 ml-xl-0 ml-4">
          <span class="red-text font-weight-bold">
            <strong><i class="fas fa-dollar-sign fa-sm"></i> {{ item.discount_price }}</strong>
          </span>
          
          <span class="grey-text">
            <small>
              <s><i class="fas fa-dollar-sign fa-sm"></i>{{ item.price }}</s>
            </small>
          </span>
        </h3>
        {% else %}
        <h3 class="h3-responsive text-center text-md-left mb-5 ml-xl-0 ml-4">
          <span class="red-text font-weight-bold">
            <strong><i class="fas fa-dollar-sign fa-sm"></i> {{ item.price }}</strong>
          </span>
        </h3>
        {% endif %}


        <!--Accordion wrapper-->
        <div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">

          <!-- Accordion card -->
          <div class="card">

            <!-- Card header -->
            <div class="card-header" role="tab" id="headingOne1">
              <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="true"
                aria-controls="collapseOne1">
                <h5 class="mb-0">
                  Description
                  <i class="fas fa-angle-down rotate-icon"></i>
                </h5>
              </a>
            </div>

            <!-- Card body -->
            <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1"
              data-parent="#accordionEx">
              <div class="card-body">
                {{ item.description }}
              </div>
            </div>
          </div>
          <!-- Accordion card -->

        </div>
        <!--/.Accordion wrapper-->

        <!-- Add to Cart -->
        <section class="color ml-4">
          <div class="mt-5">
            <p class="grey-text">Choose your color</p>
            <div class="row text-center text-md-left">

              <div class="col-md-4 col-12">
                <!--Radio group-->
                <div class="form-group">
                  <input class="form-check-input" name="group100" type="radio" id="radio100" checked="checked">
                  <label for="radio100" class="form-check-label dark-grey-text">Blue</label>
                </div>
              </div>
              <div class="col-md-4">
                <!--Radio group-->
                <div class="form-group">
                  <input class="form-check-input" name="group100" type="radio" id="radio101">
                  <label for="radio101" class="form-check-label dark-grey-text">Orange</label>
                </div>
              </div>
              <div class="col-md-4">
                <!--Radio group-->
                <div class="form-group">
                  <input class="form-check-input" name="group100" type="radio" id="radio102">
                  <label for="radio102" class="form-check-label dark-grey-text">Red</label>
                </div>
              </div>
            </div>

            <div class="row mt-3">
              <div class="col-md-12 text-center text-md-left text-md-right d-flex align-items-center justify-content-end">
                {% if request.user.is_authenticated %}
                  {% if item in wish_items %}
                  <a href="{% url 'remove-from-wish-list' item.slug %}"><i class="fas fa-heart fa-2x red-text mr-4"></i></a>
                  {% else %}                      
                  <a href="{% url 'add-to-wish-list' item.slug %}"><i class="far fa-heart fa-2x red-text mr-4"></i></a>
                  {% endif %}
                {% else %}
                  <i class="far fa-heart fa-2x red-text mr-4"></i>
                {% endif %}
                <button class="btn btn-outline-warning waves-effect btn-md ml-0">
                  <a href="{% url 'add-to-cart' item.slug %}" class="amber-text"><i class="fas fa-cart-plus mr-2" aria-hidden="true"></i> Add to cart</button></a>
              </div>
            </div>
          </div>
        </section>
        <!-- /.Add to Cart -->

      </div>

    </div>

  </section>
  <!--Section: Content-->


</div>
	
{% endblock content %}

templates/core/wish_list.html
{% extends 'base.html' %}

{% block title %}Wish list - {{ user.username }}{% endblock %}

{% block content %}

{% if wish_items %}
<div class="container mt-5">

  <!--Section: Content-->
  <section class="">

  	{% for wish_item in wish_items %}
  	<!-- Grid row -->
    <div class="row mb-5">

      <!-- Grid column -->
      <div class="col-lg-3 col-md-12 mb-lg-0 mb-4 mt-3">

				<!-- Featured image -->
        <div class="view overlay rounded z-depth-1 mb-lg-0 mb-4">
          <img class="img-fluid" src="{{ wish_item.item.image.url }}" alt="Sample image">
          <a href="{{ wish_item.item.get_absolute_url }}">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-lg-7 col-md-6 mb-md-0 mb-4 mt-xl-4">

      	<h3 class="font-weight-normal mb-3">{{ wish_item.item.title }}</h3>

      	{% if wish_item.item.discount_price %}
	        <h4 class="h4-responsive text-center text-md-left mb-2 ml-xl-0 ml-4">
	          <span class="orange-text font-weight-bold">
	            <strong><i class="fas fa-dollar-sign fa-sm"></i> {{ wish_item.item.discount_price }}</strong>
	          </span>
	          
	          <span class="grey-text">
	            <small>
	              <s><i class="fas fa-dollar-sign fa-sm"></i>{{ wish_item.item.price }}</s>
	            </small>
	          </span>
	        </h4>
	        {% else %}
	        <h4 class="h4-responsive text-center text-md-left mb-2 ml-xl-0 ml-4">
	          <span class="orange-text font-weight-bold">
	            <strong><i class="fas fa-dollar-sign fa-sm"></i> {{ wish_item.item.price }}</strong>
	          </span>
	        </h4>
         {% endif %}

         <p class="text-muted">{{ wish_item.item.description|truncatewords:35 }}</p>
         <div class="align-items-center">
	         <!-- <i class="fas fa-heart red-text fa-lg mr-3"></i> -->
	         <a type="button" class="btn btn-outline-warning waves-effect btn-md ml-0" href="{{ wish_item.item.get_absolute_url }}">About</a>
	         <a class="btn btn-outline-warning waves-effect btn-md mx-0" href="{% url 'add-to-cart' wish_item.item.slug %}"><i class="fas fa-cart-plus mr-2" aria-hidden="true"></i> Add to cart</a>
         </div>
         <p class="text-muted"><a href="{% url 'remove-from-wish-list-in-list' wish_item.item.slug %}">Remove from wish list</a></p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->
    {% endfor %}

  </section>
  <!--Section: Content-->

</div>

{% else %}
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h4 class="orange-text lead h4-responsive">You have not items in wish list.</h4>
		</div>
	</div>
</div>
{% endif %}

{% endblock %}